name: "🚀 publish"

on:
    push:
        branches:
          - main

jobs:
    release:
        name: 🚀 release
        runs-on: ubuntu-latest
        steps:
            - name: 📚 checkout
              uses: actions/checkout@v2.1.1
            - name: 🟢 node
              uses: actions/setup-node@v1.4.2
              with:
                  node-version: 14
                  registry-url: https://registry.npmjs.org
            - name: 🚀 publish
              run: npm run export
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}