name: "🚀 Publish"

on:
    push:
        branches:
          - main

jobs:
    release:
        name: Release site
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node env
              uses: actions/setup-node@v2
              with:
                  node-version: 14
                  registry-url: https://registry.npmjs.org
            - name: Export static web
              run: npm install; npm run export
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
            - name: Add CNAME
              run: touch CNAME; echo 'salomohutapea.me' > CNAME
            - name: Pushes to another repository
              uses: cpina/github-action-push-to-another-repository@master
              env:
                API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
              with:
                source-directory: '__sapper__/export'
                destination-github-username: 'salomohutapea'
                destination-repository-name: 'salomohutapea.github.io'
                user-email: hutapeasalomo@gmail.com
                target-branch: main